blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/euphony-io/euphony/discussions
    about: Ask questions and discuss with other Euphony community members
